core/urls.py
from django.urls import path
from .views import HomeView, ServicesView, ProjectsView, AboutView, BlogView, Blog_detailsView, ElementsView, ContactView


urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('services/', ServicesView.as_view(), name='services'),
    path('project/', ProjectsView.as_view(), name='project'),
    path('about/', AboutView.as_view(), name='about'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('blog_details/', Blog_detailsView.as_view(), name='blog_details'),
    path('elements/', ElementsView.as_view(), name='elements'),
    path('contact/', ContactView.as_view(), name='contact')
]

course/urls.py
from django.urls import path
from .views import Data_science_courseView
from course import views
app_name = 'Course'

urlpatterns = [
    path('Data_science/', Data_science_courseView.as_view(), name='Data_science'),
    path('services/Data_science/<int:id_course>/', views.courseDetail, name='course_detail'),
]

customadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from customadmin import views
app_name = 'custom_admin'

urlpatterns = [
    path('', views.admin_login, name='admin_login'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('', views.logout, name='sign_out_admin')

]

homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('dj-admin/', admin.site.urls),
    path('admin-login/', include('customadmin.urls')),
    path('', include('core.urls')),
    path('index/', include('course.urls')),
    path('services/', include('course.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models


# Create your models here.

class Course(models.Model):
    id_course = models.CharField(primary_key=True, max_length=999)
    name_course = models.CharField(max_length=255)
    img_course = models.ImageField(upload_to='course/%Y/%m/%d/')
    description = models.TextField(max_length=5000)
    status = models.CharField(max_length=10)
    pl_course = models.CharField(max_length=255)
    objects_course = models.CharField(max_length=255)
    target = models.TextField(max_length=5000)
    gv = models.CharField(max_length=100)
    content = models.TextField(max_length=5000)

    def __str__(self):
        return self.name_course

customadmin/models.py
from django.db import models


# Create your models here.

catalogue/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render
from django.views import View


# Create your views here.

class HomeView(View):
    def get(self, request):
        return render(request, 'assets/index.html')


class ServicesView(View):
    def get(self, request):
        return render(request, 'assets/services.html')


class ProjectsView(View):
    def get(self, request):
        return render(request, 'assets/project.html')


class AboutView(View):
    def get(self, request):
        return render(request, 'assets/about.html')


class BlogView(View):
    def get(self, request):
        return render(request, 'assets/blog.html')


class Blog_detailsView(View):
    def get(self, request):
        return render(request, 'assets/blog_details.html')


class ElementsView(View):
    def get(self, request):
        return render(request, 'assets/elements.html')


class ContactView(View):
    def get(self, request):
        return render(request, 'assets/contact.html')

course/views.py
from django.shortcuts import render
from django.views import View
from .models import Course


# Create your views here.
class Data_science_courseView(View):
    def get(self, request):
        course_1 = Course.objects.filter(id_course=1)
        course_2 = Course.objects.filter(id_course=2)
        course_3 = Course.objects.filter(id_course=3)
        course_4 = Course.objects.filter(id_course=4)
        course_5 = Course.objects.filter(id_course=5)
        course_6 = Course.objects.filter(id_course=6)
        course_7 = Course.objects.filter(id_course=7)
        course_8 = Course.objects.filter(id_course=8)
        course_9 = Course.objects.filter(id_course=9)
        course_10 = Course.objects.filter(id_course=10)
        course_11 = Course.objects.filter(id_course=11)
        course_12 = Course.objects.filter(id_course=12)
        course_13 = Course.objects.filter(id_course=13)
        return render(request, 'Course/data_science.html',
                      {'course_1': course_1,
                              'course_2': course_2,
                              'course_3': course_3,
                              'course_4': course_4,
                              'course_5': course_5,
                              'course_6': course_6,
                              'course_7': course_7,
                              'course_8': course_8,
                              'course_9': course_9,
                              'course_10': course_10,
                              'course_11': course_11,
                              'course_12': course_12,
                              'course_13': course_13, })


def courseDetail(request, id_course):
    cD = Course.objects.get(id_course=id_course)
    return render(request, 'Course/course_detail.html', {'cD': cD})

customadmin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
# @login_required(login_url='')
def admin_page(request):
    return render(request, '../templates/admin_page/Admin_page.html')


def sign_up(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        cpassword = request.POST.get('cpassword')

        if password != cpassword:
            messages.success(request, 'Sai mk')
            return render(request, '../templates/admin_register/Admin_signup.html')

        else:
            user_admin = User.objects.create_superuser(username, email, password)
            user_admin.save()
            return render(request, '../templates/admin_login/Admin_login.html')
    return render(request, '../templates/admin_register/Admin_signup.html')


def admin_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, '../templates/admin_page/Admin_page.html')
        else:
            messages.success(request, 'Try Again!!')
            return render(request, '../templates/admin_login/Admin_login.html')
    else:
        return render(request, '../templates/admin_login/Admin_login.html')


def sign_out(request):
    logout(request)
    return render(request, '../templates/admin_login/Admin_login.html')

documentdl/views.py
from django.shortcuts import render

# Create your views here.

infofeedback/views.py
from django.shortcuts import render

# Create your views here.

customadmin/templates/admin_login/Admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title> Brainwork Login Admin</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" type="image/png" href="images/icons/favicon.ico" />

<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">

<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">

<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">

<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">

<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">

<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

<link rel="stylesheet" type="text/css" href="{% static '../static/admin_login/css/util_login.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '../static/admin_login/css/main_login.css' %}">

<meta name="robots" content="noindex, follow">
<script nonce="23140f71-ef8f-4837-8df3-1fd2e7ac11ed">(function(w,d){!function(j,k,l,m){j[l]=j[l]||{};j[l].executed=[];j.zaraz={deferred:[],listeners:[]};j.zaraz.q=[];j.zaraz._f=function(n){return async function(){var o=Array.prototype.slice.call(arguments);j.zaraz.q.push({m:n,a:o})}};for(const p of["track","set","debug"])j.zaraz[p]=j.zaraz._f(p);j.zaraz.init=()=>{var q=k.getElementsByTagName(m)[0],r=k.createElement(m),s=k.getElementsByTagName("title")[0];s&&(j[l].t=k.getElementsByTagName("title")[0].text);j[l].x=Math.random();j[l].w=j.screen.width;j[l].h=j.screen.height;j[l].j=j.innerHeight;j[l].e=j.innerWidth;j[l].l=j.location.href;j[l].r=k.referrer;j[l].k=j.screen.colorDepth;j[l].n=k.characterSet;j[l].o=(new Date).getTimezoneOffset();if(j.dataLayer)for(const w of Object.entries(Object.entries(dataLayer).reduce(((x,y)=>({...x[1],...y[1]})),{})))zaraz.set(w[0],w[1],{scope:"page"});j[l].q=[];for(;j.zaraz.q.length;){const z=j.zaraz.q.shift();j[l].q.push(z)}r.defer=!0;for(const A of[localStorage,sessionStorage])Object.keys(A||{}).filter((C=>C.startsWith("_zaraz_"))).forEach((B=>{try{j[l]["z_"+B.slice(7)]=JSON.parse(A.getItem(B))}catch{j[l]["z_"+B.slice(7)]=A.getItem(B)}}));r.referrerPolicy="origin";r.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(j[l])));q.parentNode.insertBefore(r,q)};["complete","interactive"].includes(k.readyState)?zaraz.init():j.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);</script></head>
<body>
<div class="limiter">
<div class="container-login100" style="background-image: url({% static '../static/admin_login/images/bg-01.jpg' %});">
<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
<form class="login100-form validate-form" action="{% url 'custom_admin:admin_login' %}" method="POST">
	{% csrf_token %}
<span class="login100-form-title p-b-49">
Login Admin
</span>
<div class="wrap-input100 validate-input m-b-23" data-validate="Username is required">
<span class="label-input100">Username</span>
<input class="input100" type="text" name="username" placeholder="Type your username" required>
<span class="focus-input100" data-symbol="&#x1F464"></span>
</div>
<div class="wrap-input100 validate-input" data-validate="Password is required">
<span class="label-input100">Password</span>
<input class="input100" type="password" name="password" placeholder="Type your password" required>
<span class="focus-input100" data-symbol="&#128274"></span>
</div>
<div class="text-right p-t-8 p-b-31">
<a href="#">
Forgot password?
</a>
</div>
<div class="container-login100-form-btn">
<div class="wrap-login100-form-btn">
<div class="login100-form-bgbtn"></div>
<button class="login100-form-btn">
Login
</button>
</div>
</div>
<div class="txt1 text-center p-t-54 p-b-20">
<span>
Or Sign Up Using
</span>
</div>
<div class="flex-c-m">
<a href="#" class="login100-social-item bg1" style="text-decoration:none;">
<i class="fa-brands fa-facebook"></i>
</a>
<a href="#" class="login100-social-item bg2" style="text-decoration:none;">
<i class="fa-brands fa-twitter"></i>
</a>
<a href="#" class="login100-social-item bg3 " style="text-decoration:none;">
<i class="fa-brands fa-google"></i>
</a>
</div>
<div class="flex-col-c p-t-155">
<span class="txt1 p-b-17">
Or Sign Up Using
</span>
<a href="sign_up/" class="txt2">
Sign Up
</a>
</div>
</form>
</div>
</div>
</div>
<div id="dropDownSelect1"></div>

<script src="vendor/jquery/jquery-3.2.1.min.js"></script>

<script src="vendor/animsition/js/animsition.min.js"></script>

<script src="vendor/bootstrap/js/popper.js"></script>
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>

<script src="vendor/select2/select2.min.js"></script>

<script src="vendor/daterangepicker/moment.min.js"></script>
<script src="vendor/daterangepicker/daterangepicker.js"></script>

<script src="vendor/countdowntime/countdowntime.js"></script>

<script src="{% static '../static/admin_login/js/main_login.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"81b096e48b573fd0","version":"2023.10.0","token":"cd0b4b3a733644fc843ef0b185f98241"}' crossorigin="anonymous"></script>
</body>
</html>

customadmin/templates/admin_register/Admin_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title> Brainwork Signup Admin</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" type="image/png" href="images/icons/favicon.ico" />

<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">

<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">

<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">

<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">

<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">

<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

<link rel="stylesheet" type="text/css" href="{% static '../static/admin_login/css/util_login.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '../static/admin_login/css/main_login.css' %}">

<meta name="robots" content="noindex, follow">
<script nonce="23140f71-ef8f-4837-8df3-1fd2e7ac11ed">(function(w,d){!function(j,k,l,m){j[l]=j[l]||{};j[l].executed=[];j.zaraz={deferred:[],listeners:[]};j.zaraz.q=[];j.zaraz._f=function(n){return async function(){var o=Array.prototype.slice.call(arguments);j.zaraz.q.push({m:n,a:o})}};for(const p of["track","set","debug"])j.zaraz[p]=j.zaraz._f(p);j.zaraz.init=()=>{var q=k.getElementsByTagName(m)[0],r=k.createElement(m),s=k.getElementsByTagName("title")[0];s&&(j[l].t=k.getElementsByTagName("title")[0].text);j[l].x=Math.random();j[l].w=j.screen.width;j[l].h=j.screen.height;j[l].j=j.innerHeight;j[l].e=j.innerWidth;j[l].l=j.location.href;j[l].r=k.referrer;j[l].k=j.screen.colorDepth;j[l].n=k.characterSet;j[l].o=(new Date).getTimezoneOffset();if(j.dataLayer)for(const w of Object.entries(Object.entries(dataLayer).reduce(((x,y)=>({...x[1],...y[1]})),{})))zaraz.set(w[0],w[1],{scope:"page"});j[l].q=[];for(;j.zaraz.q.length;){const z=j.zaraz.q.shift();j[l].q.push(z)}r.defer=!0;for(const A of[localStorage,sessionStorage])Object.keys(A||{}).filter((C=>C.startsWith("_zaraz_"))).forEach((B=>{try{j[l]["z_"+B.slice(7)]=JSON.parse(A.getItem(B))}catch{j[l]["z_"+B.slice(7)]=A.getItem(B)}}));r.referrerPolicy="origin";r.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(j[l])));q.parentNode.insertBefore(r,q)};["complete","interactive"].includes(k.readyState)?zaraz.init():j.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);</script></head>
<body>
<div class="limiter">
<div class="container-login100" style="background-image: url({% static '../static/admin_login/images/bg-01.jpg' %});">
<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
<form class="login100-form validate-form" action="{% url 'custom_admin:sign_up' %}" method="POST">
	{% csrf_token %}
<span class="login100-form-title p-b-49">
Sign Up
</span>
<!--	login form-->

<div class="wrap-input100 validate-input m-b-23" data-validate="Username is required">
<span class="label-input100">Username</span>
<input class="input100" type="text" name="username" placeholder="Type your username" required>
<span class="focus-input100" data-symbol="&#x1F464"></span>
</div>
<div class="wrap-input100 validate-input m-b-23" data-validate="Email is required">
<span class="label-input100">Email</span>
<input class="input100" type="email" name="email" placeholder="Type your email" required>
<span class="focus-input100" data-symbol="&#9993"></span>
</div>
<div class="wrap-input100 validate-input" data-validate="Password is required">
<span class="label-input100">Password</span>
<input class="input100" type="password" name="password" placeholder="Type your password" required>
<span class="focus-input100" data-symbol="&#128274"></span>
</div>
<div class="wrap-input100 validate-input " data-validate="Password is required">
<span class="label-input100">Confirm your Password</span>
<input class="input100" type="password" name="cpassword" placeholder="Type your password" required>
<span class="focus-input100" data-symbol="&#128274"></span>
</div>
<!--</form>-->
<!--	login form-->
<div class="text-right p-t-8 p-b-31">
<a href="#">
Forgot password?
</a>
</div>
<div class="container-login100-form-btn">
<div class="wrap-login100-form-btn">
<div class="login100-form-bgbtn"></div>
<button class="login100-form-btn">
Sign Up
</button>
</div>
</div>
</form>
<div class="txt1 text-center p-t-54 p-b-20">
<span>
Or Sign Up Using
</span>
</div>
<div class="flex-c-m">
<a href="#" class="login100-social-item bg1" style="text-decoration:none;">
<i class="fa-brands fa-facebook"></i>
</a>
<a href="#" class="login100-social-item bg2" style="text-decoration:none;">
<i class="fa-brands fa-twitter"></i>
</a>
<a href="#" class="login100-social-item bg3 " style="text-decoration:none;">
<i class="fa-brands fa-google"></i>
</a>
</div>
<div class="flex-col-c p-t-155">
<a href="/admin-login" class="txt2">
Back to Login
</a>
</div>
</form>
</div>
</div>
</div>
<div id="dropDownSelect1"></div>

<script src="vendor/jquery/jquery-3.2.1.min.js"></script>

<script src="vendor/animsition/js/animsition.min.js"></script>

<script src="vendor/bootstrap/js/popper.js"></script>
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>

<script src="vendor/select2/select2.min.js"></script>

<script src="vendor/daterangepicker/moment.min.js"></script>
<script src="vendor/daterangepicker/daterangepicker.js"></script>

<script src="vendor/countdowntime/countdowntime.js"></script>

<script src="{% static '../static/admin_login/js/main_login.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"81b096e48b573fd0","version":"2023.10.0","token":"cd0b4b3a733644fc843ef0b185f98241"}' crossorigin="anonymous"></script>
</body>
</html>

templates/Course/course_detail.html
{% include 'assets/header.html' %}
{% load static %}
<main>
<div class="slider-area">
<div class="single-slider slider-bg3 hero-overly slider-height2 d-flex align-items-center">
<div class="container">
<div class="row justify-content-center ">
<div class="col-xl-12">
<div class="hero-caption hero-caption2 text-center">
<h2>Khóa học chuyển đổi số, công nghệ</h2>
</div>
</div>
</div>
</div>
</div>
</div>
 <section class="blog_area section-padding">
<div class="container">
<div class="row">
<div class="col-lg-8 mb-5 mb-lg-0">
<div class="blog_left_sidebar">
<article class="blog_item">
<div class="blog_item_img">
<img class="card-img rounded-0" src="{{ cD.img_course.url }}" alt>
<a href="#" class="blog_item_date">
<h3>15</h3>
<p>Jan</p>
</a>
</div>
<div class="blog_details">
<ul class="blog-info-link">
<li><a href="#"><i class="fa fa-user"></i> Travel, Lifestyle</a></li>
<li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>
</ul>
</div>
</article>
<!-- ff-->
<article class="course_content">
<h2 class="text_name">{{ cD.name_course }}</h2>
<p class="text_course">{{cD.description}}</p>
<h3 class="part_course">Đối tượng tham dự</h3>
<p class="text_course">{{cD.objects_course}}</p>
<h3 class="part_course">Mục Tiêu</h3>
<p class="text_course">{{cD.target}}</p>
<h3 class="part_course">Thông tin giảng viên</h3>
<p class="text_course">{{cD.gv}}</p>
<h3 class="part_course">Nội dung</h3>
<p class="text_course">{{cD.content}}</p>
</article>
<!-- ff-->
</div>
</div>
<div class="col-lg-4">
<div class="blog_right_sidebar">
<aside class="single_sidebar_widget search_widget">
<h2 class="select_course">Hình thức học</h2>
<hr class="line_course">
<div class="tag-course">
<a href="#">Học trực tuyến</a>
<a href="#">Học tập trung</a>
<a href="#">E-Learning</a>
</div>
</aside>
<!--    ...-->
<aside class="single_sidebar_widget search_widget">
<h2 class="select_course">Tải thông tin khóa học bản PDF</h2>
<hr class="line_course">
<label class="dowload_course" role="button">Tải xuống <i aria-hidden="true" class="fa-solid fa-download fa-beat"></i> </label>
</aside>
<!-- ...-->
 <aside class="single_sidebar_widget search_widget">
<h2 class="select_course">Yêu cầu báo giá</h2>
<hr class="line_course">
</aside>
<!-- ...-->
<aside class="single_sidebar_widget post_category_widget">
<h4 class="select_course">Khoá học liên quan</h4>
<ul class="list cat-list">
<li>
<a href="/index/services/Data_science/1" class="d-flex">
<p class="text_course">Công nghệ 5G và các ứng dụng</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(803)</p>
</a>
</li>
<li>
<a href="/index/services/Data_science/2" class="d-flex">
<p class="text_course">Điện toán đám mây</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(705)</p>
</a>
</li>
<li>
<a href="/index/services/Data_science/3" class="d-flex">
<p class="text_course">Chuyển đổi số trong vận hành các nhà máy điện</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(604)</p>
</a>
</li>
<li>
<a href="/index/services/Data_science/4" class="d-flex">
<p class="text_course">Trí tuệ nhân tạo (AI) và học máy (Machine learning)</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(836)</p>
</a>
</li>
<li>
<a href="/index/services/Data_science/5" class="d-flex">
<p class="text_course">Ứng dụng IOT và AI trong đô thị thông minh</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(660)</p>
</a>
</li>
<li>
<a href="/index/services/Data_science/6" class="d-flex">
<p class="text_course">Công nghệ Blockchain</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(782)</p>
</a>
</li>
 <li>
<a href="/index/services/Data_science/7" class="d-flex">
<p class="text_course">Các giải pháp công nghệ mới cho nền kinh tế</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(430)</p>
</a>
</li>
 <li>
<a href="/index/services/Data_science/8" class="d-flex">
<p class="text_course">Phân tích dữ liệu lớn</p>
<p class="text_course"><i class="fa-solid fa-eye"></i>(434)</p>
</a>
</li>
</ul>
</aside>
</div>
</div>
</div>
</div>
</section>
</main>

{% include 'assets/footer.html' %}

templates/assets/index.html
{% include 'assets/base.html' %}
{% load static %}
{% block content %}
{% endblock %}

templates/assets/project.html
{% include 'assets/header.html' %}
{% load static %}
<main>

<div class="slider-area">
<div class="single-slider slider-bg4 hero-overly slider-height2 d-flex align-items-center">
<div class="container">
<div class="row justify-content-center ">
<div class="col-xl-12">

<div class="hero-caption hero-caption2 text-center">
<h2>Projects</h2>
</div>
</div>
</div>
</div>
</div>
</div>


<div class="guest-house top-padding">
<div class="container">
<div class="row">
<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-8 col-sm-9">
<div class="section-tittle mb-70">
<span>Projects</span>
<h2>See Latest Projects For our Client</h2>
</div>
</div>
</div>
</div>
<div class="container-fluid">
<div class="row">
<div class="col-md-6 col-sm-6 p-0">
<div class="single-location">
<img src="{% static 'assets/img/gallery/gallery1.jpg' %}" alt>
<div class="guest-contents">
<p>Gas & Oil</p>
<h3><a href="#">Power and Energy</a></h3>
</div>
</div>
</div>
<div class="col-md-6 col-sm-6 p-0">
<div class="single-location">
<img src="{% static 'assets/img/gallery/gallery2.jpg' %}" alt>
<div class="guest-contents">
<p>Gas & Oil</p>
<h3><a href="#">Power and Energy</a></h3>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 p-0">
<div class="single-location">
<img src="{% static 'assets/img/gallery/gallery3.jpg' %}" alt>
<div class="guest-contents">
<p>Gas & Oil</p>
<h3><a href="#">Power and Energy</a></h3>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 p-0">
<div class="single-location">
<img src="{% static 'assets/img/gallery/gallery4.jpg' %}" alt>
<div class="guest-contents">
<p>Gas & Oil</p>
<h3><a href="#">Power and Energy</a></h3>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 p-0">
<div class="single-location">
<img src="{% static 'assets/img/gallery/gallery5.jpg' %}" alt>
<div class="guest-contents">
<p>Gas & Oil</p>
<h3><a href="#">Power and Energy</a></h3>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-lg-12 p-0">
<a href="#" class="btn_10 w-100 text-center">More Project<img src="{% static 'assets/img/icon/right-arrow.svg' %}" alt></a>
</div>
</div>
</div>
</div>

</main>
{% include 'assets/footer.html' %}